# Generated by Django 5.0.6 on 2026-08-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_id', models.CharField(help_text="Slug used in Razorpay notes, e.g. 'gut-reset'", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField(help_text='Price in INR')),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='ebook_covers/')),
                ('pdf_file', models.FileField(blank=True, upload_to='ebooks/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_combo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('combo_items', models.ManyToManyField(blank=True, help_text='For combo packs: individual eBooks included in this combo', related_name='part_of_combos', to='ebooks.ebook')),
            ],
            options={
                'verbose_name': 'eBook',
                'verbose_name_plural': 'eBooks',
                'ordering': ['is_combo', 'title'],
            },
        ),
    ]
